# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='AWS Account ID', max_length=12, unique=True)),
                ('account_name', models.CharField(blank=True, help_text='Account name or alias', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is actively monitored')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_id'],
            },
        ),
        migrations.CreateModel(
            name='VPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpc_id', models.CharField(help_text='VPC ID', max_length=21, unique=True)),
                ('region', models.CharField(help_text='AWS Region', max_length=50)),
                ('cidr_block', models.CharField(help_text='CIDR block', max_length=18)),
                ('owner_account', models.CharField(help_text='Owner account ID', max_length=12)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default VPC')),
                ('state', models.CharField(help_text='VPC state', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vpc_id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_id', models.CharField(help_text='Security Group ID', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Security Group name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Security Group description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_groups', to='resources.vpc')),
            ],
            options={
                'ordering': ['sg_id'],
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet_id', models.CharField(help_text='Subnet ID', max_length=24, unique=True)),
                ('name', models.CharField(blank=True, help_text='Subnet name tag', max_length=255)),
                ('cidr_block', models.CharField(help_text='CIDR block', max_length=18)),
                ('availability_zone', models.CharField(help_text='Availability Zone', max_length=50)),
                ('owner_account', models.CharField(help_text='Owner account ID', max_length=12)),
                ('state', models.CharField(help_text='Subnet state', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='resources.vpc')),
            ],
            options={
                'ordering': ['subnet_id'],
            },
        ),
        migrations.CreateModel(
            name='ENI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eni_id', models.CharField(help_text='ENI ID', max_length=21, unique=True)),
                ('name', models.CharField(blank=True, help_text='ENI name tag', max_length=255)),
                ('description', models.TextField(blank=True, help_text='ENI description')),
                ('interface_type', models.CharField(help_text='Interface type (e.g., interface, gateway_load_balancer)', max_length=50)),
                ('status', models.CharField(help_text='ENI status', max_length=20)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address', max_length=17)),
                ('private_ip_address', models.GenericIPAddressField(help_text='Primary private IP address')),
                ('public_ip_address', models.GenericIPAddressField(blank=True, help_text='Public IP address if assigned', null=True)),
                ('attached_resource_id', models.CharField(blank=True, help_text='ID of attached resource (instance, load balancer, etc.)', max_length=255)),
                ('attached_resource_type', models.CharField(blank=True, help_text='Type of attached resource', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enis', to='resources.subnet')),
            ],
            options={
                'ordering': ['eni_id'],
            },
        ),
        migrations.CreateModel(
            name='ENISecondaryIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Secondary IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_ips', to='resources.eni')),
            ],
            options={
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='ENISecurityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eni_security_groups', to='resources.eni')),
                ('security_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sg_enis', to='resources.securitygroup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vpc',
            constraint=models.UniqueConstraint(fields=('vpc_id', 'region'), name='unique_vpc_region'),
        ),
        migrations.AddConstraint(
            model_name='enisecuritygroup',
            constraint=models.UniqueConstraint(fields=('eni', 'security_group'), name='unique_eni_security_group'),
        ),
        migrations.AddConstraint(
            model_name='enisecondaryip',
            constraint=models.UniqueConstraint(fields=('eni', 'ip_address'), name='unique_eni_secondary_ip'),
        ),
    ]