# Generated by Django 4.2.7 on 2025-10-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enisecondaryip',
            name='unique_eni_secondary_ip',
        ),
        migrations.RemoveConstraint(
            model_name='enisecuritygroup',
            name='unique_eni_security_group',
        ),
        migrations.RemoveConstraint(
            model_name='vpc',
            name='unique_vpc_region',
        ),
        migrations.AlterUniqueTogether(
            name='enisecondaryip',
            unique_together={('eni', 'ip_address')},
        ),
        migrations.AlterUniqueTogether(
            name='enisecuritygroup',
            unique_together={('eni', 'security_group')},
        ),
        migrations.AlterUniqueTogether(
            name='vpc',
            unique_together={('vpc_id', 'region')},
        ),
    ]
