# Generated by Django 4.2.7 on 2025-10-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_enisecondaryip_unique_eni_secondary_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccount',
            name='last_polled',
            field=models.DateTimeField(blank=True, help_text='Last time resources were polled for this account', null=True),
        ),
    ]
