# Generated by Django 4.2.7 on 2025-10-08 18:43

from django.db import migrations


def populate_last_polled(apps, schema_editor):
    """Set last_polled to created_at for existing accounts"""
    AWSAccount = apps.get_model('resources', 'AWSAccount')
    for account in AWSAccount.objects.all():
        account.last_polled = account.created_at
        account.save()


def reverse_populate_last_polled(apps, schema_editor):
    """Reverse migration - set last_polled to None"""
    AWSAccount = apps.get_model('resources', 'AWSAccount')
    AWSAccount.objects.all().update(last_polled=None)


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_add_last_polled_to_account'),
    ]

    operations = [
        migrations.RunPython(populate_last_polled, reverse_populate_last_polled),
    ]
