# Generated by Django 4.2.7 on 2025-10-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_add_last_polled_to_account'),
    ]

    operations = [
    ]
