# Generated by Django 4.2.7 on 2025-10-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_populate_last_polled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGroupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('ingress', 'Ingress'), ('egress', 'Egress')], help_text='Rule type (ingress/egress)', max_length=10)),
                ('protocol', models.CharField(help_text='Protocol (tcp, udp, icmp, etc.)', max_length=10)),
                ('from_port', models.IntegerField(blank=True, help_text='From port', null=True)),
                ('to_port', models.IntegerField(blank=True, help_text='To port', null=True)),
                ('source_type', models.CharField(help_text='Source type (cidr, sg, prefix-list, etc.)', max_length=20)),
                ('source_value', models.TextField(help_text='Source value (CIDR, security group ID, etc.)')),
                ('description', models.TextField(blank=True, help_text='Rule description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='resources.securitygroup')),
            ],
            options={
                'ordering': ['rule_type', 'protocol', 'from_port'],
                'unique_together': {('security_group', 'rule_type', 'protocol', 'from_port', 'to_port', 'source_type', 'source_value')},
            },
        ),
    ]
