# Generated by Django 4.2.7 on 2025-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_add_security_group_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='eni',
            name='owner_account',
            field=models.CharField(default='', help_text='Owner account ID', max_length=12),
        ),
    ]
