# Generated by Django 4.2.26 on 2025-11-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_eni_owner_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(help_text='EC2 Instance ID', max_length=19, unique=True)),
                ('name', models.CharField(blank=True, help_text='Instance name tag', max_length=255)),
                ('instance_type', models.CharField(help_text='Instance type (e.g., t2.micro, m5.large)', max_length=50)),
                ('state', models.CharField(help_text='Instance state (running, stopped, etc.)', max_length=20)),
                ('region', models.CharField(help_text='AWS Region', max_length=50)),
                ('availability_zone', models.CharField(help_text='Availability Zone', max_length=50)),
                ('private_ip_address', models.GenericIPAddressField(blank=True, help_text='Primary private IP address', null=True)),
                ('public_ip_address', models.GenericIPAddressField(blank=True, help_text='Public IP address if assigned', null=True)),
                ('platform', models.CharField(blank=True, help_text='Platform (e.g., windows, linux)', max_length=50)),
                ('launch_time', models.DateTimeField(blank=True, help_text='Instance launch time', null=True)),
                ('owner_account', models.CharField(help_text='Owner account ID', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='resources.subnet')),
                ('vpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='resources.vpc')),
            ],
            options={
                'ordering': ['instance_id'],
                'unique_together': {('instance_id', 'region')},
            },
        ),
        migrations.AddField(
            model_name='eni',
            name='ec2_instance',
            field=models.ForeignKey(blank=True, help_text='Attached EC2 instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enis', to='resources.ec2instance'),
        ),
    ]
