# Generated by Django 4.2.26 on 2025-11-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_ec2instance_eni_ec2_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='tags',
            field=models.JSONField(blank=True, default=dict, help_text='AWS tags as key-value pairs'),
        ),
        migrations.AddField(
            model_name='eni',
            name='tags',
            field=models.JSONField(blank=True, default=dict, help_text='AWS tags as key-value pairs'),
        ),
        migrations.AddField(
            model_name='securitygroup',
            name='tags',
            field=models.JSONField(blank=True, default=dict, help_text='AWS tags as key-value pairs'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='tags',
            field=models.JSONField(blank=True, default=dict, help_text='AWS tags as key-value pairs'),
        ),
        migrations.AddField(
            model_name='vpc',
            name='tags',
            field=models.JSONField(blank=True, default=dict, help_text='AWS tags as key-value pairs'),
        ),
    ]
