# Generated by Django 5.2.8 on 2025-11-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_ec2instance_tags_eni_tags_securitygroup_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccount',
            name='external_id',
            field=models.CharField(blank=True, help_text='External ID for role assumption (optional, for additional security)', max_length=1224),
        ),
        migrations.AddField(
            model_name='awsaccount',
            name='role_arn',
            field=models.CharField(blank=True, help_text='IAM Role ARN to assume when discovering resources in this account', max_length=2048),
        ),
    ]
