# Generated by Django 5.2.9 on 2025-12-17 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_add_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID', max_length=255, null=True, unique=True)),
                ('task_type', models.CharField(choices=[('single', 'Single Account'), ('bulk', 'Bulk Discovery')], default='single', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('regions', models.JSONField(default=list, help_text='List of regions to scan')),
                ('result_summary', models.JSONField(blank=True, default=dict, help_text='Summary of discovered resources')),
                ('error_message', models.TextField(blank=True, help_text='Error details if task failed')),
                ('total_accounts', models.IntegerField(default=1)),
                ('completed_accounts', models.IntegerField(default=0)),
                ('failed_accounts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_tasks', to='resources.awsaccount')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='resources.discoverytask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='resources_d_status_edaa02_idx'), models.Index(fields=['account', 'created_at'], name='resources_d_account_55eb81_idx'), models.Index(fields=['initiated_by', 'created_at'], name='resources_d_initiat_7cedc1_idx')],
            },
        ),
    ]
