# Generated by Django 5.2.9 on 2025-12-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_discoverytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccount',
            name='auth_method',
            field=models.CharField(choices=[('credentials', 'Access Keys (Manual)'), ('instance_role', 'EC2 Instance Role')], default='credentials', help_text='Authentication method for polling this account', max_length=20),
        ),
        migrations.AddField(
            model_name='awsaccount',
            name='default_regions',
            field=models.JSONField(blank=True, default=list, help_text="Default regions to poll for this account (e.g., ['us-east-1', 'us-west-2'])"),
        ),
        migrations.AddField(
            model_name='awsaccount',
            name='default_role_name',
            field=models.CharField(blank=True, default='PaloInventoryInspectionRole', help_text='Default IAM role name to assume in this account (used with instance role auth)', max_length=255),
        ),
    ]
