# Generated by Django 5.2.9 on 2026-02-04 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_awsaccount_auth_method_awsaccount_default_regions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eni',
            name='subnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enis', to='resources.subnet'),
        ),
    ]
