# Generated by Django 5.2.9 on 2026-02-04 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_eni_subnet_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='subnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='resources.subnet'),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='vpc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='resources.vpc'),
        ),
    ]
