# Generated by Django 5.2.9 on 2026-02-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_ec2_vpc_subnet_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccount',
            name='auto_poll_disabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether auto-polling is disabled due to consecutive failures'),
        ),
        migrations.AddField(
            model_name='awsaccount',
            name='consecutive_failures',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of consecutive poll failures'),
        ),
        migrations.AddField(
            model_name='awsaccount',
            name='last_failure_reason',
            field=models.TextField(blank=True, help_text='Reason for last poll failure'),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this resource was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this resource was last seen during polling', null=True),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='missed_polls',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of consecutive polls where this resource was not found'),
        ),
        migrations.AddField(
            model_name='eni',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this resource was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='eni',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this resource was last seen during polling', null=True),
        ),
        migrations.AddField(
            model_name='eni',
            name='missed_polls',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of consecutive polls where this resource was not found'),
        ),
        migrations.AddField(
            model_name='securitygroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this resource was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='securitygroup',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this resource was last seen during polling', null=True),
        ),
        migrations.AddField(
            model_name='securitygroup',
            name='missed_polls',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of consecutive polls where this resource was not found'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this resource was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this resource was last seen during polling', null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='missed_polls',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of consecutive polls where this resource was not found'),
        ),
        migrations.AddField(
            model_name='vpc',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this resource was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='vpc',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this resource was last seen during polling', null=True),
        ),
        migrations.AddField(
            model_name='vpc',
            name='missed_polls',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of consecutive polls where this resource was not found'),
        ),
        # Composite indexes for efficient soft delete queries by owner
        migrations.AddIndex(
            model_name='eni',
            index=models.Index(fields=['owner_account', 'deleted_at'], name='eni_owner_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='ec2instance',
            index=models.Index(fields=['owner_account', 'deleted_at'], name='ec2_owner_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='vpc',
            index=models.Index(fields=['owner_account', 'deleted_at'], name='vpc_owner_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='subnet',
            index=models.Index(fields=['owner_account', 'deleted_at'], name='subnet_owner_deleted_idx'),
        ),
    ]
