# Generated by Django 5.2.9 on 2026-02-04

from django.db import migrations
from django.db.models import F


def populate_last_seen_at(apps, schema_editor):
    """Set last_seen_at = updated_at for existing records."""
    for model_name in ['VPC', 'Subnet', 'ENI', 'EC2Instance', 'SecurityGroup']:
        Model = apps.get_model('resources', model_name)
        Model.objects.filter(last_seen_at__isnull=True).update(last_seen_at=F('updated_at'))


def reverse_populate(apps, schema_editor):
    """Reverse: set last_seen_at back to null."""
    for model_name in ['VPC', 'Subnet', 'ENI', 'EC2Instance', 'SecurityGroup']:
        Model = apps.get_model('resources', model_name)
        Model.objects.all().update(last_seen_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_soft_delete_and_account_failure_tracking'),
    ]

    operations = [
        migrations.RunPython(populate_last_seen_at, reverse_populate),
    ]
