# Generated by Django 5.2.9 on 2026-02-05 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_populate_last_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=10)),
                ('category', models.CharField(choices=[('resource_created', 'Resource Created'), ('resource_updated', 'Resource Updated'), ('resource_skipped', 'Resource Skipped'), ('resource_soft_deleted', 'Resource Soft Deleted'), ('resource_resurrected', 'Resource Resurrected'), ('ec2_link_preserved', 'EC2 Link Preserved'), ('lookup_failed', 'Lookup Failed'), ('account_error', 'Account Error'), ('account_success', 'Account Success')], db_index=True, max_length=30)),
                ('message', models.TextField()),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=30)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=30)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_logs', to='resources.awsaccount')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='resources.discoverytask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'level'], name='discoverylog_task_level_idx'), models.Index(fields=['account', 'created_at'], name='discoverylog_acct_created_idx'), models.Index(fields=['resource_type', 'resource_id'], name='discoverylog_res_type_id_idx')],
            },
        ),
    ]
